### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by cfoote2667** [daniel-pro/Latitude-5310-EFI#1]
Hey, thank you for this EFI zip, it works very nicely on my Latitude 5310. Like you, I'm having the same issue with the touchpad, did you ever figure it out? It's interesting, I found someone who had a 5300 and has the touchpad working perfectly, but I've been trying to reverse engineer his config.plist and other things to see what was done differently...

**Comment by cfoote2667** [comment]
Wanted to follow up in case you or anyone else reading this needs a hand after spending 10 hours trying to find a fix...

A great project kext called AlpsHID solves our issues

https://github.com/blankmac/AlpsHID

Thank you to @juico for this kext

**Comment by daniel-pro** [comment]
Thanks for your contribution @cfoote2667 
Do you know how to make a PR ?
In that way we could integrate your findings with this repo...
